config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activities

  root 'main#index'

  resources :wishes

end

app/models/ability.rb
class Ability
  include CanCan::Ability

   def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wish.rb
class Wish < ActiveRecord::Base
	 validates :user_wish, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @duration = 360

  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:task, :ittake, :avatar)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
include MainHelper
  def index
  	@current_time = Time.now
    wish_times 
    @wish_times = [@one_11, @two_22, @three_33, @four_44, @five_55, @ten_10, @eleven_11, @twelve_12p, @one_11p, @two_22p, @three_33p, @four_44p, @five_55p, @ten_10p, @eleven_11p, @twelve_12]
    # @wish_times = ['01:11', '02:22', '03:33', '04:44', '05:55', '10:10', '11:11', '12:12']
    @activities = Activity.all

    minutes_until_wish_times
    closest_wish_time
  end


end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]
  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:user_wish)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper

  def wish_times 
	@one_11 = Chronic.parse('1:11am')
    @one_11p = Chronic.parse('1:11pm')

    @two_22 = Chronic.parse('2:22am')
    @two_22p = Chronic.parse('2:22pm')

    @three_33 = Chronic.parse('3:33am')
    @three_33p = Chronic.parse('3:33pm')

    @four_44 = Chronic.parse('4:44am')
    @four_44p = Chronic.parse('4:44pm')

    @five_55 = Chronic.parse('5:55am')
    @five_55p = Chronic.parse('5:55pm')

    @ten_10 = Chronic.parse('10:10am')
    @ten_10p = Chronic.parse('10:10pm')

    @eleven_11 = Chronic.parse('11:11am')
    @eleven_11p = Chronic.parse('11:11pm')

    @twelve_12 = Chronic.parse('12:12am')
    @twelve_12p = Chronic.parse('12:12pm')
  end

  def minutes_until_wish_times
  	@durations = []

  	@wish_times.each do |time| 
      @duration = time - Time.now
	  @duration = (@duration / 60)  #time in minutes
	  @durations.push([@duration,time])
	   # puts "************"
    #    puts @duration
    #    puts "************"

    end
       # puts "************"
       # print @durations
       # puts "************"
  end #end of minutes_until_wish_times

  def closest_wish_time
  	@pos_durations = []

  	@durations.each do |duration|
	  	if duration[0] > 0
	     @pos_durations.push([duration[0],duration[1]])
	   #   puts "************"
	  	# puts duration[0]
	  	# puts "************"
	  	end
     end
     
     @closest_pair = @pos_durations.min
     @closest_wish_time = @closest_pair[1]
     @closest_duration = @closest_pair[0]
	   # puts "************"
    #    print @closest_duration
    #    print @closest_wish_time
    #    puts "************"
  end # end of closest_wish_time

end # end of helper

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :ittake %><br>
    <%= f.time_select :ittake %>
  </div>
  <div class="field form-group">
    <%= f.label :photo %> <br>
    <%= f.file_field :avatar %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Avg Time</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.task %></td>
        <td><%= activity.ittake.min %> minutes</td>
        
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>


<p><%= image_tag @activity.avatar.url(:thumb) %><br>
  <strong>Task:</strong>
  <%= @activity.task %>
</p>

<p>
  <strong>Avg Time:</strong>
  <%= @activity.ittake.min %> minutes
</p>



<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Makeawish</title>
    <%= javascript_include_tag 'application'  %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="/">Home</a></li>
            <li role="presentation"><a href="/activities">Activities</a></li>
<!--             <li role="presentation"><a href="#">Contact</a></li>
 -->        <li role="presentation"><%= link_to 'Make A Wish!', new_wish_path %></li> 
          </ul>
        </nav>
        <%= image_tag 'genie.png', width: '5%', class: 'pull-left' %><h3 style="padding:10px 0 0 70px;">Time Genie<sup>&#8482;</sup> </h3>
      </div>


<div class="container">
<%= yield %>
</div>

<footer style="border-top:1px solid #ccc;margin-top:100px;padding:20px 0;">
<div class="row">
  <div class="col-md-9">
    <% if user_signed_in? %>
      You are logged in as <%= current_user.email %> | 
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
    	You are not logged in.
    	<%= link_to "Log in", user_session_path %>
    <% end %>
  </div>
  <div class="col-md-3">
    <p align="right">&copy; 2014 Rodia Productions</p>
  </div>
</div>

</footer>

<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.0.0/moment.min.js"></script>

</body>
</html>

app/views/main/index.html.erb
<!-- <h1>Make A Wish</h1>
 -->
 <script type="text/javascript">    
   $(document).ready(function() {
      setTimeout(function(){ window.location.reload();
      }, 60000);
     // alert('REFRESHED!')
   });
</script>

<br clear="all">

<!-- Add right column wish stream -->

<div class="row">
  <div class="col-md-4">
  	<div id="clock" class="light">
	    <div class="display">
	        <div class="weekdays"></div>
	        <div class="ampm"></div>
	        <div class="alarm"></div>
	        <div class="digits"></div>
	    </div>
    </div>

	<% @wish_times.each do |time| %>
	 <% if @current_time.to_s(:time) == time.to_s(:time) %>
		<p align="center"><%= link_to 'Make A Wish!', new_wish_path, class: 'btn btn-primary btn-lg' %></p>
	  <% end %>
	<% end %>


  </div>
  <div class="col-md-8">
	<p>Genie grants wishes when the hour and minute fields match. Craft beer bespoke kale chips, listicle drinking vinegar church-key whatever bitters chambray polaroid. Selfies hoodie iPhone lomo yr pork belly fingerstache, letterpress tattooed mumblecore stumptown. Taxidermy shabby chic fap, street art pork belly flexitarian small batch yr drinking vinegar cred before they sold out messenger bag master cleanse.</p>
	<p> Chillwave distillery direct trade Blue Bottle jean shorts. Ugh art party tousled, stumptown meditation disrupt kale chips you probably haven't heard of them hoodie irony. Keytar single-origin coffee tousled, health goth Brooklyn Pinterest Marfa. Cronut cornhole bicycle rights 3 wolf moon.</p>
  </div>
 </div>

<div class="row">
	<div class="col-md-12">
		<% if @closest_duration > 0 %>
	     <h2 class="alert alert-info" align="center"><%= number_to_human(@closest_duration) %> minutes until Genie grants your wish!</h2>
	     <% else %>
	     <h2 class="alert alert-danger" align="center">OMG Go wish!!</h2>
	   <% end %>

		<p><strong>Stick around and wait for the wish button to appear. Until then you could:</strong></p>
		<% @activities.each do |activity| %>
		  <div class="col-md-4">
			<div class="well" align="center">
				<h4 style="text-transform:uppercase"><%= activity.task %></h4>
				<h1><%=  number_to_human(@closest_duration / activity.ittake.min) %></h1> times
		   </div>
		</div>
		<% end %>
	</div>
</div>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field form-group">
    <%#= f.text_field :user_wish, class: 'form-control' %>
  </div> -->
<!--   <div class="actions">
 -->    <%#= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
    <%#= f.submit(class: 'btn btn-primary btn-lg') do %>
      <!--<i class="glyphicon glyphicon-send"></i>-->
    <%#end %>

    <div class="input-group">
       <%= f.text_field :user_wish, class: 'form-control' %>
      <span class="input-group-btn">
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        <i class="glyphicon glyphicon-send"></i>
       <% end %>
      </span>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<h1>Editing Wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>
</div>
</div>

app/views/wishes/index.html.erb
<p id="notice"><%= notice %></p>

<br clear="all"/>
<h3>I wish:</h3>

<table class="table">

  <tbody>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= wish.user_wish %></td>
        <% if can? :update, wish %>
        <td><%= link_to 'Show', wish %></td>
        <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
        <td><%= link_to 'Destroy', wish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Time: <%= @time %></h1>

<br>
<% if can? :update, @wishes %>
<%= link_to 'New Wish', new_wish_path %>
<% end %>

app/views/wishes/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<h1>I wish:</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show All Wishes', wishes_path %>
</div>
</div>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<h3>I wish: <%= @wish.user_wish %></h3>

<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>
</div>
</div>